In [2]:
%pip install splink

Requirement already satisfied: splink in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (3.9.11)
Requirement already satisfied: Jinja2>=3.0.3 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (3.1.2)
Requirement already satisfied: altair<6.0.0,>=5.0.1 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (5.2.0)
Requirement already satisfied: duckdb>=0.8.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (0.9.2)
Requirement already satisfied: jsonschema<5.0,>=3.2 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (4.17.3)
Requirement already satisfied: pandas>1.3.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (1.5.3)
Requirement already satisfied: phonetics<2.0.0,>=1.0.5 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (1.0.5)
Requirement already satisfied: sqlglot<19.0.0,>=13.0.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (18.17.0)
Requirement already satisfied: numpy in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from altair<6.0.0,>=5.0.1->splink) (1.26.3)
Requirement already satisfied: packaging in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from altair<6.0.0,>=5.0.1->splink) (23.2)
Requirement already satisfied: toolz in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from altair<6.0.0,>=5.0.1->splink) (0.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from Jinja2>=3.0.3->splink) (2.1.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from jsonschema<5.0,>=3.2->splink) (23.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from jsonschema<5.0,>=3.2->splink) (0.20.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from pandas>1.3.0->splink) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from pandas>1.3.0->splink) (2023.3.post1)
Requirement already satisfied: six>=1.5 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas>1.3.0->splink) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

# Data prerequisites

Splink requires that you clean your data and assign unique IDs to rows before linking.

In [1]:
import pandas as pd

In [2]:
df_l = pd.read_csv('hospital_account_info.csv')
df_r = pd.read_csv('hospital_reimbursement.csv')

### Unique IDs

In [3]:
df_l

,Account_Num,Facility Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership
0,10605,SAGE MEMORIAL HOSPITAL,STATE ROUTE 264 SOUTH 191,GANADO,AZ,86505,APACHE,(928) 755-4541,Critical Access Hospitals,Voluntary non-profit - Private
1,24250,WOODRIDGE BEHAVIORAL CENTER,600 NORTH 7TH STREET,WEST MEMPHIS,AR,72301,CRITTENDEN,(870) 394-4113,Psychiatric,Proprietary
2,10341,DOUGLAS GARDENS HOSPITAL,5200 NE 2ND AVE,MIAMI,FL,33137,MIAMI-DADE,(305) 751-8626,Acute Care Hospitals,Voluntary non-profit - Private
3,81101,SUNCOAST BEHAVIORAL HEALTH CENTER,4480 51ST ST W,BRADENTON,FL,34210,MANATEE,(941) 792-2222,Psychiatric,Proprietary
4,39835,TREASURE VALLEY HOSPITAL,8800 WEST EMERALD STREET,BOISE,ID,83704,ADA,(208) 373-5000,Acute Care Hospitals,Proprietary
...,...,...,...,...,...,...,...,...,...,...
5334,92281,JEWISH HOSPITAL - SHELBYVILLE,727 HOSPITAL DRIVE,SHELBYVILLE,KY,40065,SHELBY,(502) 647-4300,Acute Care Hospitals,Voluntary non-profit - Private
5335,65248,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,MONTGOMERY,(937) 641-3450,Childrens,Voluntary non-profit - Private
5336,92377,NORTH TEXAS STATE HOSPITAL,6515 KEMP BLVD,WICHITA FALLS,TX,76308,WICHITA,(940) 692-1220,Psychiatric,Government - State
5337,71562,GULF BREEZE HOSPITAL,1110 GULF BREEZE PKWY,GULF BREEZE,FL,32561,SANTA ROSA,(850) 934-2000,Acute Care Hospitals,Voluntary non-profit - Other
5338,51586,I-70 COMMUNITY HOSPITAL,"105 HOSPITAL DRIVE, BUILDING B",SWEET SPRINGS,MO,65351,SALINE,(660) 335-4700,Critical Access Hospitals,Proprietary

In [4]:
df_l = df_l.rename(columns={"Account_Num":"unique_id", "Facility Name":"Facility_Name"})
df_l

,unique_id,Facility_Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership
0,10605,SAGE MEMORIAL HOSPITAL,STATE ROUTE 264 SOUTH 191,GANADO,AZ,86505,APACHE,(928) 755-4541,Critical Access Hospitals,Voluntary non-profit - Private
1,24250,WOODRIDGE BEHAVIORAL CENTER,600 NORTH 7TH STREET,WEST MEMPHIS,AR,72301,CRITTENDEN,(870) 394-4113,Psychiatric,Proprietary
2,10341,DOUGLAS GARDENS HOSPITAL,5200 NE 2ND AVE,MIAMI,FL,33137,MIAMI-DADE,(305) 751-8626,Acute Care Hospitals,Voluntary non-profit - Private
3,81101,SUNCOAST BEHAVIORAL HEALTH CENTER,4480 51ST ST W,BRADENTON,FL,34210,MANATEE,(941) 792-2222,Psychiatric,Proprietary
4,39835,TREASURE VALLEY HOSPITAL,8800 WEST EMERALD STREET,BOISE,ID,83704,ADA,(208) 373-5000,Acute Care Hospitals,Proprietary
...,...,...,...,...,...,...,...,...,...,...
5334,92281,JEWISH HOSPITAL - SHELBYVILLE,727 HOSPITAL DRIVE,SHELBYVILLE,KY,40065,SHELBY,(502) 647-4300,Acute Care Hospitals,Voluntary non-profit - Private
5335,65248,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,MONTGOMERY,(937) 641-3450,Childrens,Voluntary non-profit - Private
5336,92377,NORTH TEXAS STATE HOSPITAL,6515 KEMP BLVD,WICHITA FALLS,TX,76308,WICHITA,(940) 692-1220,Psychiatric,Government - State
5337,71562,GULF BREEZE HOSPITAL,1110 GULF BREEZE PKWY,GULF BREEZE,FL,32561,SANTA ROSA,(850) 934-2000,Acute Care Hospitals,Voluntary non-profit - Other
5338,51586,I-70 COMMUNITY HOSPITAL,"105 HOSPITAL DRIVE, BUILDING B",SWEET SPRINGS,MO,65351,SALINE,(660) 335-4700,Critical Access Hospitals,Proprietary

In [5]:
df_r

,Provider_Num,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,839987,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,118,20855.61,5026.19,4115.52
1,519118,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,43,13289.09,5413.63,4490.93
2,733073,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,73,22261.60,4922.18,4021.79
3,201752,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,12,10901.33,5343.50,4284.17
4,678488,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,74,28117.95,5947.12,4819.53
...,...,...,...,...,...,...,...,...,...,...
2692,403227,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,700 SCOTT & WHITE DRIVE,COLLEGE STATION,TX,77845,37,20837.57,6389.76,3927.62
2693,797810,WALNUT HILL MEDICAL CENTER,7502 GREENVILLE AVENUE,DALLAS,TX,75231,52,32453.85,21927.08,4423.52
2694,611900,"BAY AREA REGIONAL MEDICAL CENTER, LLC",200 BLOSSOM STREET,WEBSTER,TX,77598,31,33006.84,19222.26,4497.16
2695,693781,RESOLUTE HEALTH HOSPITAL,"555 CREEKSIDE XING,",NEW BRAUNFELS,TX,78130,19,34370.00,9910.16,4531.37
2696,322584,BAYLOR SCOTT & WHITE MEDICAL CENTER - MARBLE F...,810 W HIGHWAY 71,MARBLE FALLS,TX,78654,18,17398.72,4650.44,3500.67

In [6]:
df_r = df_r.rename(columns={"Provider_Num":"unique_id"})
df_r

,unique_id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,839987,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,118,20855.61,5026.19,4115.52
1,519118,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,43,13289.09,5413.63,4490.93
2,733073,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,73,22261.60,4922.18,4021.79
3,201752,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,12,10901.33,5343.50,4284.17
4,678488,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,74,28117.95,5947.12,4819.53
...,...,...,...,...,...,...,...,...,...,...
2692,403227,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,700 SCOTT & WHITE DRIVE,COLLEGE STATION,TX,77845,37,20837.57,6389.76,3927.62
2693,797810,WALNUT HILL MEDICAL CENTER,7502 GREENVILLE AVENUE,DALLAS,TX,75231,52,32453.85,21927.08,4423.52
2694,611900,"BAY AREA REGIONAL MEDICAL CENTER, LLC",200 BLOSSOM STREET,WEBSTER,TX,77598,31,33006.84,19222.26,4497.16
2695,693781,RESOLUTE HEALTH HOSPITAL,"555 CREEKSIDE XING,",NEW BRAUNFELS,TX,78130,19,34370.00,9910.16,4531.37
2696,322584,BAYLOR SCOTT & WHITE MEDICAL CENTER - MARBLE F...,810 W HIGHWAY 71,MARBLE FALLS,TX,78654,18,17398.72,4650.44,3500.67

### Conformant input datasets

In [7]:
df_r = df_r.rename(columns={"Provider Name":"Facility_Name", "Provider Street Address":"Address", "Provider City":"City", "Provider State":"State"})
df_r

,unique_id,Facility_Name,Address,City,State,Provider Zip Code,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,839987,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,118,20855.61,5026.19,4115.52
1,519118,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,43,13289.09,5413.63,4490.93
2,733073,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,73,22261.60,4922.18,4021.79
3,201752,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,12,10901.33,5343.50,4284.17
4,678488,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,74,28117.95,5947.12,4819.53
...,...,...,...,...,...,...,...,...,...,...
2692,403227,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,700 SCOTT & WHITE DRIVE,COLLEGE STATION,TX,77845,37,20837.57,6389.76,3927.62
2693,797810,WALNUT HILL MEDICAL CENTER,7502 GREENVILLE AVENUE,DALLAS,TX,75231,52,32453.85,21927.08,4423.52
2694,611900,"BAY AREA REGIONAL MEDICAL CENTER, LLC",200 BLOSSOM STREET,WEBSTER,TX,77598,31,33006.84,19222.26,4497.16
2695,693781,RESOLUTE HEALTH HOSPITAL,"555 CREEKSIDE XING,",NEW BRAUNFELS,TX,78130,19,34370.00,9910.16,4531.37
2696,322584,BAYLOR SCOTT & WHITE MEDICAL CENTER - MARBLE F...,810 W HIGHWAY 71,MARBLE FALLS,TX,78654,18,17398.72,4650.44,3500.67

In [8]:
df_l = df_l.drop(columns={'ZIP Code', 'County Name', 'Phone Number', 'Hospital Type', 'Hospital Ownership'})
df_l

,unique_id,Facility_Name,Address,City,State
0,10605,SAGE MEMORIAL HOSPITAL,STATE ROUTE 264 SOUTH 191,GANADO,AZ
1,24250,WOODRIDGE BEHAVIORAL CENTER,600 NORTH 7TH STREET,WEST MEMPHIS,AR
2,10341,DOUGLAS GARDENS HOSPITAL,5200 NE 2ND AVE,MIAMI,FL
3,81101,SUNCOAST BEHAVIORAL HEALTH CENTER,4480 51ST ST W,BRADENTON,FL
4,39835,TREASURE VALLEY HOSPITAL,8800 WEST EMERALD STREET,BOISE,ID
...,...,...,...,...,...
5334,92281,JEWISH HOSPITAL - SHELBYVILLE,727 HOSPITAL DRIVE,SHELBYVILLE,KY
5335,65248,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH
5336,92377,NORTH TEXAS STATE HOSPITAL,6515 KEMP BLVD,WICHITA FALLS,TX
5337,71562,GULF BREEZE HOSPITAL,1110 GULF BREEZE PKWY,GULF BREEZE,FL
5338,51586,I-70 COMMUNITY HOSPITAL,"105 HOSPITAL DRIVE, BUILDING B",SWEET SPRINGS,MO

In [9]:
df_r = df_r.drop(columns={'Provider Zip Code', 'Total Discharges', 'Average Covered Charges', 'Average Total Payments', 'Average Medicare Payments'})
df_r

,unique_id,Facility_Name,Address,City,State
0,839987,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL
1,519118,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL
2,733073,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL
3,201752,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL
4,678488,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL
...,...,...,...,...,...
2692,403227,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,700 SCOTT & WHITE DRIVE,COLLEGE STATION,TX
2693,797810,WALNUT HILL MEDICAL CENTER,7502 GREENVILLE AVENUE,DALLAS,TX
2694,611900,"BAY AREA REGIONAL MEDICAL CENTER, LLC",200 BLOSSOM STREET,WEBSTER,TX
2695,693781,RESOLUTE HEALTH HOSPITAL,"555 CREEKSIDE XING,",NEW BRAUNFELS,TX
2696,322584,BAYLOR SCOTT & WHITE MEDICAL CENTER - MARBLE F...,810 W HIGHWAY 71,MARBLE FALLS,TX

In [10]:
df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2697 entries, 0 to 2696
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   unique_id      2697 non-null   int64
 1   Facility_Name  2697 non-null   object
 2   Address        2697 non-null   object
 3   City           2697 non-null   object
 4   State          2697 non-null   object
dtypes: int64(1), object(4)
memory usage: 105.5+ KB

In [11]:
df_l.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5339 entries, 0 to 5338
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   unique_id      5339 non-null   int64
 1   Facility_Name  5339 non-null   object
 2   Address        5339 non-null   object
 3   City           5339 non-null   object
 4   State          5339 non-null   object
dtypes: int64(1), object(4)
memory usage: 208.7+ KB

### Ensure nulls are consistently and correctly represented

In [12]:
df_l.isna().sum()

unique_id        0
Facility_Name    0
Address          0
City             0
State            0
dtype: int64

In [13]:
df_r.isna().sum()

unique_id        0
Facility_Name    0
Address          0
City             0
State            0
dtype: int64

# Exploratory analysis

### Read the data

In [14]:

df = pd.concat([df_r, df_l], axis=0)
df

,unique_id,Facility_Name,Address,City,State
0,839987,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL
1,519118,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL
2,733073,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL
3,201752,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL
4,678488,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL
...,...,...,...,...,...
5334,92281,JEWISH HOSPITAL - SHELBYVILLE,727 HOSPITAL DRIVE,SHELBYVILLE,KY
5335,65248,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH
5336,92377,NORTH TEXAS STATE HOSPITAL,6515 KEMP BLVD,WICHITA FALLS,TX
5337,71562,GULF BREEZE HOSPITAL,1110 GULF BREEZE PKWY,GULF BREEZE,FL
5338,51586,I-70 COMMUNITY HOSPITAL,"105 HOSPITAL DRIVE, BUILDING B",SWEET SPRINGS,MO

### Instantiate the linker

In [15]:
from splink.duckdb.linker import DuckDBLinker

In [16]:
linker = DuckDBLinker(df)

### Analyse missingness

In [17]:
linker.missingness_chart()

alt.LayerChart(...)

No missing values !

### Analyse the distribution of values in your data

The distribution of values in your data is important for two main reasons:

- Columns with higher cardinality (number of distinct values) are usually more useful for data linking. For instance, date of birth is a much stronger linkage variable than gender.

- The skew of values is important. If you have a city column that has 1,000 distinct values, but 75% of them are London, this is much less useful for linkage than if the 1,000 values were equally distributed

In [18]:
linker.profile_columns(top_n=10, bottom_n=5)

alt.VConcatChart(...)

Here the facility name and Address have high cardinalities which is good + No skew

# Blocking

### Splink tools to help choose your blocking rules

In [19]:
from splink.duckdb.blocking_rule_library import block_on
import altair as alt

In [20]:
settings = {"link_type":"dedupe_only"}
linker = DuckDBLinker(df, settings)

In [21]:
blocking_rule_1 = block_on(["State", "City"])
count = linker.count_num_comparisons_from_blocking_rule(blocking_rule_1)
print(f"Number of comparisons generated by '{blocking_rule_1.blocking_rule_sql}': {count:,.0f}")

Number of comparisons generated by '(l."State" = r."State") AND (l."City" = r."City")': 16,812

In [22]:
blocking_rule_2 = block_on("Address")
count = linker.count_num_comparisons_from_blocking_rule(blocking_rule_2)
print(f"Number of comparisons generated by '{blocking_rule_2.blocking_rule_sql}': {count:,.0f}")

Number of comparisons generated by 'l."Address" = r."Address"': 2,653

In [25]:
blocking_rule_3 = block_on("Facility_Name")
count = linker.count_num_comparisons_from_blocking_rule(blocking_rule_3)
print(f"Number of comparisons generated by '{blocking_rule_3.blocking_rule_sql}': {count:,.0f}")

Number of comparisons generated by 'l."Facility_Name" = r."Facility_Name"': 3,272

### Counting the number of comparisons created by a list of blocking rules

In [26]:
blocking_rules = [blocking_rule_1, blocking_rule_2, blocking_rule_3]
linker.cumulative_num_comparisons_from_blocking_rules_chart(blocking_rules)

alt.Chart(...)

# Estimating model parameters

### Comparisons

In [27]:
import splink.duckdb.comparison_library as cl
import splink.duckdb.comparison_template_library as ctl

In [28]:
facility_name_comparison = ctl.name_comparison("Facility_Name")
print(facility_name_comparison.human_readable_description)

Comparison 'Exact match vs. Facility_Name within levenshtein threshold 1 vs. Facility_Name within damerau-levenshtein threshold 1 vs. Facility_Name within jaro_winkler thresholds 0.9, 0.8 vs. anything else' of "Facility_Name".
Similarity is assessed using the following ComparisonLevels:
    - 'Null' with SQL rule: "Facility_Name_l" IS NULL OR "Facility_Name_r" IS NULL
    - 'Exact match Facility_Name' with SQL rule: "Facility_Name_l" = "Facility_Name_r"
    - 'Damerau_levenshtein <= 1' with SQL rule: damerau_levenshtein("Facility_Name_l", "Facility_Name_r") <= 1
    - 'Jaro_winkler_similarity >= 0.9' with SQL rule: jaro_winkler_similarity("Facility_Name_l", "Facility_Name_r") >= 0.9
    - 'Jaro_winkler_similarity >= 0.8' with SQL rule: jaro_winkler_similarity("Facility_Name_l", "Facility_Name_r") >= 0.8
    - 'All other comparisons' with SQL rule: ELSE

### Specifying the full settings dictionary

In [29]:
settings = {
    "link_type" : "dedupe_only",
    "comparisons": [
        ctl.name_comparison("Facility_Name"),
        cl.exact_match('State', term_frequency_adjustments=True),
        cl.exact_match('City', term_frequency_adjustments=True),
        ctl.name_comparison("Address")
    ],
    "blocking_rules_to_generate_predictions": [
        block_on(["State", "City"]),
        block_on("Address"),
        block_on("Facility_Name")
    ],
    "retain_matching_columns" : True,
    "retain_intermediate_calculation_columns": True,
}
linker = DuckDBLinker(df, settings)

### Estimate the parameters of the model

Now that we have specified our linkage model, we need to estimate the probability_two_random_records_match, u, and m parameters.

- The probability_two_random_records_match parameter is the probability that two records taken at random from your input data represent a match (typically a very small number).

- The u values are the proportion of records falling into each ComparisonLevel amongst truly non-matching records.

- The m values are the proportion of records falling into each ComparisonLevel amongst truly matching records

In [36]:
deterministic_rules = [
    "l.Facility_Name = r.Facility_Name and levenshtein(l.Address, r.Address) <=2",
    "l.Address = r.Address and levenshtein(l.Facility_Name, r.Facility_Name) <=2",
    "l.City = r.City and l.State = r.State and levenshtein(l.Address, r.Address) <=2"
]

linker.estimate_probability_two_random_records_match(deterministic_rules, recall=0.7)

Probability two random records match is estimated to be  0.000116.
This means that amongst all possible pairwise record comparisons, one in 8,638.85 are expected to match.  With 32,284,630 total possible comparisons, we expect a total of around 3,737.14 matching pairs

In [37]:
linker.estimate_u_using_random_sampling(max_pairs=1e6)

----- Estimating u probabilities using random sampling -----

Estimated u probabilities using random sampling

Your model is not yet fully trained. Missing estimates for:
    - Facility_Name (no m values are trained).
    - State (no m values are trained).
    - City (no m values are trained).
    - Address (no m values are trained).

In [38]:
training_blocking_rule = block_on(["City","State"])
training_session_fname_sname = linker.estimate_parameters_using_expectation_maximisation(training_blocking_rule)

----- Starting EM training session -----

Estimating the m probabilities of the model by blocking on:
(l."City" = r."City") AND (l."State" = r."State")

Parameter estimates will be made for the following comparison(s):
    - Facility_Name
    - Address

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules:
    - State
    - City

Iteration 1: Largest change in params was 0.14 in probability_two_random_records_match
Iteration 2: Largest change in params was -0.0722 in the m_probability of Facility_Name, level `Exact match Facility_Name`
Iteration 3: Largest change in params was 0.0468 in the m_probability of Facility_Name, level `All other comparisons`
Iteration 4: Largest change in params was -0.0215 in the m_probability of Address, level `Exact match Address`
Iteration 5: Largest change in params was -0.00891 in the m_probability of Address, level `Exact match Address`
Iteration 6: Largest change in params was -0.00538 in the m_probability of Address, level `Exact match Address`
Iteration 7: Largest change in params was -0.00434 in the m_probability of Address, level `Exact match Address`
Iteration 8: Largest change in params was -0.00391 in the m_probability of Address, level `Exact match Address`
Iteration 9: Largest change in params was -0.00367 in the m_probability of Address, level `Exact match Address`
Iteration 10: Largest change in params was 0.00356 in the m_probability of Address, level `All other comparisons`
Iteration 11: Largest change in params was 0.00343 in the m_probability of Address, level `All other comparisons`
Iteration 12: Largest change in params was 0.00322 in the m_probability of Address, level `All other comparisons`
Iteration 13: Largest change in params was 0.00292 in the m_probability of Address, level `All other comparisons`
Iteration 14: Largest change in params was 0.00256 in the m_probability of Address, level `All other comparisons`
Iteration 15: Largest change in params was 0.00218 in the m_probability of Address, level `All other comparisons`
Iteration 16: Largest change in params was 0.00182 in the m_probability of Address, level `All other comparisons`
Iteration 17: Largest change in params was 0.00148 in the m_probability of Address, level `All other comparisons`
Iteration 18: Largest change in params was 0.00119 in the m_probability of Address, level `All other comparisons`
Iteration 19: Largest change in params was 0.00094 in the m_probability of Address, level `All other comparisons`
Iteration 20: Largest change in params was 0.000738 in the m_probability of Address, level `All other comparisons`
Iteration 21: Largest change in params was 0.000575 in the m_probability of Address, level `All other comparisons`
Iteration 22: Largest change in params was 0.000446 in the m_probability of Address, level `All other comparisons`
Iteration 23: Largest change in params was 0.000344 in the m_probability of Address, level `All other comparisons`
Iteration 24: Largest change in params was 0.000265 in the m_probability of Address, level `All other comparisons`
Iteration 25: Largest change in params was 0.000204 in the m_probability of Address, level `All other comparisons`

EM converged after 25 iterations

Your model is not yet fully trained. Missing estimates for:
    - State (no m values are trained).
    - City (no m values are trained).

In [39]:
training_blocking_rule = block_on("Facility_Name")
training_session_dob = linker.estimate_parameters_using_expectation_maximisation(training_blocking_rule)

----- Starting EM training session -----

Estimating the m probabilities of the model by blocking on:
l."Facility_Name" = r."Facility_Name"

Parameter estimates will be made for the following comparison(s):
    - State
    - City
    - Address

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules:
    - Facility_Name

Iteration 1: Largest change in params was 0.691 in probability_two_random_records_match
Iteration 2: Largest change in params was -0.00541 in the m_probability of Address, level `Exact match Address`
Iteration 3: Largest change in params was 8.5e-05 in the m_probability of Address, level `All other comparisons`

EM converged after 3 iterations

Your model is fully trained. All comparisons have at least one estimate for their m and u values

### Visualising model parameters

In [40]:
linker.match_weights_chart()

alt.VConcatChart(...)

In [41]:
linker.m_u_parameters_chart()

alt.HConcatChart(...)

In [42]:
settings = linker.save_model_to_json("saved_splink_model_from_demo.json", overwrite=True)

In [43]:
linker.unlinkables_chart()

alt.LayerChart(...)

# Predicting results

### Predicting match weights using the trained model

In [47]:
df_predictions = linker.predict(threshold_match_probability=0.7)
df_predictions.as_pandas_dataframe()

,match_weight,match_probability,unique_id_l,unique_id_r,Facility_Name_l,Facility_Name_r,gamma_Facility_Name,bf_Facility_Name,State_l,State_r,...,gamma_City,tf_City_l,tf_City_r,bf_City,bf_tf_adj_City,Address_l,Address_r,gamma_Address,bf_Address,match_key
0,1.236728,0.702083,15447,48423,SURGICAL SPECIALTY CENTER AT COORDINATED HEALTH,LEHIGH VALLEY HOSPITAL,0,0.132839,PA,PA,...,1,0.000622,0.000622,1229.392143,1.307313,1503 CEDAR CREST BOULEVARD,1200 SOUTH CEDAR CREST BOULEVARD,1,3.808617,0
1,1.288896,0.709590,60458,70160,"KANSAS SPINE & SPECIALTY HOSPITAL, LLC",KANSAS SURGERY & RECOVERY CENTER,0,0.132839,KS,KS,...,1,0.001120,0.001120,1229.392143,0.726285,3333 NORTH WEBB ROAD,2770 NORTH WEBB ROAD,1,3.808617,0
2,1.311439,0.712800,11035,550921,SAINT JOSEPH HOSPITAL,PRESBYTERIAN ST LUKES MEDICAL CENTER,0,0.132839,CO,CO,...,1,0.001493,0.001493,1229.392143,0.544714,1375 E 19TH AVE,1719 E 19TH AVE,1,3.808617,0
3,1.311439,0.712800,36013,46468,CHILDREN'S HOSPITAL COLORADO,UNIVERSITY OF COLORADO HOSPITAL AUTHORITY,0,0.132839,CO,CO,...,1,0.001493,0.001493,1229.392143,0.544714,13123 E 16TH AVE,12605 E 16TH AVE,1,3.808617,0
4,1.311439,0.712800,11035,731274,SAINT JOSEPH HOSPITAL,ROSE MEDICAL CENTER,0,0.132839,CO,CO,...,1,0.001493,0.001493,1229.392143,0.544714,1375 E 19TH AVE,4567 E 9TH AVENUE,1,3.808617,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2989,33.563715,1.000000,67617,636173,NORTHWESTERN MEDICAL CENTER INC,NORTHWESTERN MEDICAL CENTER INC,4,7244.997918,VT,VT,...,1,0.000249,0.000249,1229.392143,3.268282,133 FAIRFIELD STREET,133 FAIRFIELD STREET,4,10313.958063,0
2990,33.563715,1.000000,60441,677847,RUTLAND REGIONAL MEDICAL CENTER,RUTLAND REGIONAL MEDICAL CENTER,4,7244.997918,VT,VT,...,1,0.000249,0.000249,1229.392143,3.268282,160 ALLEN ST,160 ALLEN ST,4,10313.958063,0
2991,33.563715,1.000000,32761,406681,OUR LADY OF FATIMA HOSPITAL,OUR LADY OF FATIMA HOSPITAL,4,7244.997918,RI,RI,...,1,0.000249,0.000249,1229.392143,3.268282,200 HIGH SERVICE AVENUE,200 HIGH SERVICE AVENUE,4,10313.958063,0
2992,33.853222,1.000000,22652,332764,BEEBE MEDICAL CENTER,BEEBE MEDICAL CENTER,4,7244.997918,DE,DE,...,1,0.000249,0.000249,1229.392143,3.268282,424 SAVANNAH RD,424 SAVANNAH RD,4,10313.958063,0
2993,33.853222,1.000000,51209,891017,NANTICOKE MEMORIAL HOSPITAL,NANTICOKE MEMORIAL HOSPITAL,4,7244.997918,DE,DE,...,1,0.000249,0.000249,1229.392143,3.268282,801 MIDDLEFORD RD,801 MIDDLEFORD RD,4,10313.958063,0

# Visualising predictions

### Waterfall chart

In [48]:
records_to_view  = df_predictions.as_record_dict(limit=5)
linker.waterfall_chart(records_to_view, filter_nulls=False)

alt.LayerChart(...)

### Comparison viewer dashboard

In [49]:
linker.comparison_viewer_dashboard(df_predictions, "scv.html", overwrite=True)